### ISSUE TITLE
Notifications when it is about to be your turn to dj

### ISSUE THREAD

**Issue by Hoarsey** [DubPlus/DubPlus#15]
I think it makes a chat notification already, but if it could send a notification through chrome that would be really awesome!

**Comment by coryshaw1** [comment]
This is planned for an upcoming release. Will keep this issue open until it is live.

**Comment by coryshaw1** [comment]
Feature is a part of #18 

Looking to see what the best name would be for this feature. I ended up calling it Queue Notification, but I'm thinking DJ Alert or something similar may be good too? Looking for thoughts on this.

**Comment by Hoarsey** [comment]
DJ Alert seems fitting. Could include a notification, just a sound, or
maybe both.

Connor Kaufmann
Virginia Polytechnic and State University Class of 2016
College of Natural Resources
267.221.7206

**Comment by coryshaw1** [comment]
Closed with the merge of #18!

Thanks for the help @Hoarsey
