### ISSUE TITLE
AFK cool-down 

### ISSUE THREAD

**Issue by FranciscoG** [DubPlus/DubPlus#43]
set a cool down to AFK auto-response so it's not chat spamming.

Now the question is,  is this a hard-coded or do we allow users to set their own cool-down?

I lean toward just a simple hard-coded timeout that we choose.  Maybe like 10 seconds?  20 seconds?

**Comment by FranciscoG** [comment]
wait a minute,  is this already done here?
 https://github.com/DubPlus/DubPlus/blob/master/src/js/modules/afk.js#L34

**Comment by coryshaw1** [comment]
Nothing is checking that state is the problem

**Comment by FranciscoG** [comment]
yeah.. just needs a quick check at the top of the function.  I can add that in.

So we're all good with just 3 seconds?  (that's what's in there now)

**Comment by coryshaw1** [comment]
3 seconds is enough in my opinion, we can change to more in the future if needed

**Comment by FranciscoG** [comment]
my mistake, it was set to 180,000ms, which is 3minutes.. not 3 seconds

**Comment by coryshaw1** [comment]
Closed by #44 and #45
