### ISSUE TITLE
Hide gif-selfie icon

### ISSUE THREAD

**Issue by coryshaw1** [DubPlus/DubPlus#46]
Hide the gif-selfie icon in the chat bar

![https://i.imgur.com/kpL4tg8.png](https://i.imgur.com/kpL4tg8.png)

**Comment by FranciscoG** [comment]
does anyone ever use that? I've never seen it used. Wonder what the analytics are on its use

**Comment by FranciscoG** [comment]
we can add this to 2.0.0,  should be easy

**Comment by FranciscoG** [comment]
in 2.0.0 beta
