### ISSUE TITLE
Feature Request: Notification on PMs

### ISSUE THREAD

**Issue by diremuffin** [DubPlus/DubPlus#7]
Not sure how plausible this is, but it would be nice to get a ping or something when I get a PM. If I don't have the window up, there's no way to know!

If you need clarification, let me know, but I'm hoping this is pretty self-explanatory. ;)

**Comment by FranciscoG** [comment]
I really like this idea!  This all depends if Dubtrack offers up an event we could bind to when receiving a new PM.  I do see that there's a "realtime:new-message" event which is different from their "realtime:chat-message" event.  I wonder if that relates to PM.  I'll have to test it out.

**Comment by FranciscoG** [comment]
testing was a success!

**Comment by FranciscoG** [comment]
add in #9
